<?php


namespace Elyt\Admin;


use Carbon\Laravel\ServiceProvider;
use Monolog\Logger;


class AdminServiceProvider extends ServiceProvider
{
    public function register()
    {


        /*
     $this->app->singleton('Test', function () {
         return new Test();
     });
*/
    }


    public function boot()
    {
        return parent::boot(); // TODO: Change the autogenerated stub
    }
}